import crypto from 'crypto'
import { Prisma } from '@prisma/client'
import prisma from '../../config/db'
import { InventoryError, attachHoldsToOrder, getCheckoutHolds } from '../inventory/inventory.service'
import { failOrder, getPaymentProvider, startPayment } from '../payments/payments.service'

export const PAYMENT_WINDOW_MINUTES = 15

export class OrderError extends Error {
  constructor(message: string, public status = 400) {
    super(message)
  }
}

const D = Prisma.Decimal
const fee = (price: Prisma.Decimal, percent: Prisma.Decimal) =>
  price.mul(percent).div(100).toDecimalPlaces(2, Prisma.Decimal.ROUND_HALF_UP)

/**
 * The cart: what the user holds for an event, itemised (FR-TKT-08, FR-CHK-02/03, BR-16).
 * The service fee is per ticket, set per category (BR-05), and shown separately from the price.
 */
export const getCart = async (userId: string, eventId: string) => {
  const holds = await getCheckoutHolds(userId, eventId)

  const lines = holds.map((h) => {
    const unitFee = fee(h.ticketCategory.price, h.ticketCategory.serviceFeePercent)
    return {
      holdId: h.id,
      ticketCategoryId: h.ticketCategory.id,
      category: h.ticketCategory.name,
      seat: h.seat ? `${h.seat.section}-${h.seat.row}-${h.seat.number}` : null,
      quantity: h.quantity,
      unitPrice: h.ticketCategory.price,
      unitServiceFee: unitFee,
      serviceFeePercent: h.ticketCategory.serviceFeePercent,
      lineTotal: h.ticketCategory.price.add(unitFee).mul(h.quantity),
    }
  })

  const subtotal = lines.reduce((s, l) => s.add(l.unitPrice.mul(l.quantity)), new D(0))
  const serviceFeeTotal = lines.reduce((s, l) => s.add(l.unitServiceFee.mul(l.quantity)), new D(0))
  return {
    eventId,
    lines,
    ticketCount: lines.reduce((n, l) => n + l.quantity, 0),
    subtotal,
    serviceFeeTotal,
    total: subtotal.add(serviceFeeTotal),
    currency: 'EGP',
  }
}

// Human-readable, unambiguous: no 0/O, 1/I/L (FR-CHK-12)
const REF_ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'
const newReference = () =>
  'HF-' + Array.from({ length: 6 }, () => REF_ALPHABET[crypto.randomInt(REF_ALPHABET.length)]).join('')

const orderView = {
  id: true,
  reference: true,
  eventId: true,
  status: true,
  subtotal: true,
  serviceFeeTotal: true,
  total: true,
  currency: true,
  expiresAt: true,
  paidAt: true,
  createdAt: true,
  items: { select: { ticketCategoryId: true, quantity: true, unitPrice: true, serviceFeePercent: true, serviceFeeAmount: true } },
} as const

export interface CheckoutInput {
  eventId: string
  /** generated by the frontend once per checkout attempt; resending it never creates a second order (FR-CHK-10) */
  idempotencyKey: string
  /** the policy modal was acknowledged (FR-CHK-04) */
  policyAccepted: boolean
  /** one name per ticket, per hold (FR-TKT-06) */
  attendees: { holdId: string; names: string[] }[]
}

/**
 * Turns the user's held tickets into an order and starts the payment.
 * Holds stay reserved until the payment deadline.
 */
export const checkout = async (userId: string, input: CheckoutInput) => {
  if (!input.idempotencyKey || input.idempotencyKey.length > 100) throw new OrderError('A valid idempotencyKey is required')

  // Same checkout sent again (double click, network retry): return the first order, never a second
  const existing = await prisma.order.findUnique({ where: { idempotencyKey: input.idempotencyKey }, select: { ...orderView, userId: true } })
  if (existing) return resumeExisting(userId, existing)

  if (input.policyAccepted !== true) throw new OrderError('Please read and accept the event policy to continue')

  const cart = await getCart(userId, input.eventId)
  if (cart.lines.length === 0) throw new OrderError('You have no tickets held for this event. Please select tickets again.', 409)

  // Every held line needs one attendee name per ticket
  const namesByHold = new Map(input.attendees?.map((a) => [a.holdId, a.names]) ?? [])
  const attach = cart.lines.map((l) => {
    const names = (namesByHold.get(l.holdId) ?? []).map((n) => String(n).trim())
    if (names.length !== l.quantity || names.some((n) => n.length < 2 || n.length > 200)) {
      throw new OrderError(`Please give a full name for each of the ${l.quantity} ticket(s) in ${l.category}`)
    }
    return { id: l.holdId, attendeeNames: names }
  })

  // One order item per category
  const items = new Map<string, { quantity: number; unitPrice: Prisma.Decimal; serviceFeePercent: Prisma.Decimal; serviceFeeAmount: Prisma.Decimal }>()
  for (const l of cart.lines) {
    const item = items.get(l.ticketCategoryId)
    if (item) item.quantity += l.quantity
    else items.set(l.ticketCategoryId, { quantity: l.quantity, unitPrice: l.unitPrice, serviceFeePercent: l.serviceFeePercent, serviceFeeAmount: l.unitServiceFee })
  }

  const expiresAt = new Date(Date.now() + PAYMENT_WINDOW_MINUTES * 60_000)

  let order
  for (let attempt = 0; ; attempt++) {
    try {
      order = await prisma.$transaction(async (tx) => {
        const created = await tx.order.create({
          data: {
            reference: newReference(),
            userId,
            eventId: input.eventId,
            subtotal: cart.subtotal,
            serviceFeeTotal: cart.serviceFeeTotal,
            total: cart.total,
            currency: cart.currency,
            idempotencyKey: input.idempotencyKey,
            policyAcceptedAt: new Date(),
            expiresAt,
            items: { create: [...items].map(([ticketCategoryId, i]) => ({ ticketCategoryId, ...i })) },
          },
          select: orderView,
        })
        await attachHoldsToOrder(tx, userId, created.id, expiresAt, attach)
        return created
      }, { maxWait: 20_000, timeout: 20_000 })
      break
    } catch (e) {
      if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2002') {
        const target = String(e.meta?.['target'] ?? '')
        if (target.includes('idempotency')) {
          // two identical requests raced; the other one created the order
          const raced = await prisma.order.findUniqueOrThrow({ where: { idempotencyKey: input.idempotencyKey }, select: { ...orderView, userId: true } })
          return resumeExisting(userId, raced)
        }
        if (target.includes('reference') && attempt < 5) continue // reference collision, try another
      }
      if (e instanceof InventoryError) throw new OrderError(e.message, 409)
      throw e
    }
  }

  try {
    const payment = await startPayment(order)
    return { order, payment }
  } catch (e) {
    console.error('Could not start payment:', e)
    await failOrder(order.id)
    throw new OrderError('The payment service is unavailable. Your tickets were released; please try again.', 502)
  }
}

const resumeExisting = async (userId: string, order: { id: string; userId: string; status: string } & Record<string, unknown>) => {
  if (order.userId !== userId) throw new OrderError('This checkout key is already used', 409)
  const { userId: _, ...view } = order
  const payment = await prisma.payment.findUnique({ where: { orderId: order.id }, select: { providerTxId: true } })
  const session =
    order.status === 'PENDING' && payment?.providerTxId
      ? await getPaymentProvider().resumePayment(payment.providerTxId)
      : null
  return { order: view, payment: session }
}

/**
 * The user's orders, newest first
 */
export const getMyOrders = async (userId: string) => {
  return prisma.order.findMany({
    where: { userId },
    select: { ...orderView, event: { select: { id: true, name: true, startAt: true } } },
    orderBy: { createdAt: 'desc' },
  })
}

/**
 * One of the user's orders, with its tickets once paid
 */
export const getMyOrder = async (userId: string, orderId: string) => {
  const order = await prisma.order.findFirst({
    where: { id: orderId, userId },
    select: {
      ...orderView,
      event: { select: { id: true, name: true, startAt: true } },
      payment: { select: { status: true, provider: true } },
    },
  })
  if (!order) throw new OrderError('Order not found', 404)
  return order
}

/**
 * The buyer gives up before paying: stop the payment and release the places
 */
export const cancelMyOrder = async (userId: string, orderId: string) => {
  const order = await prisma.order.findFirst({
    where: { id: orderId, userId },
    select: { status: true, payment: { select: { providerTxId: true } } },
  })
  if (!order) throw new OrderError('Order not found', 404)
  if (order.status !== 'PENDING') throw new OrderError('Only unpaid orders can be cancelled')

  const txId = order.payment?.providerTxId
  if (txId) {
    const p = getPaymentProvider()
    await p.cancel(txId)
    if ((await p.getStatus(txId)) === 'SUCCEEDED') throw new OrderError('This order has already been paid', 409)
  }
  await failOrder(orderId, 'CANCELLED')
}
